### ISSUE TITLE
Mis-spelled constant in eeConstants.js

### ISSUE THREAD

**Issue by scrubjay** [STRML/Healthcare.gov-Marketplace#11]
In the file eeConstants.js there is a mis-spelling:

var MINIMUM_STUDENT_AGE=19;
var MAXIMIM_STUDENT_AGE=22;

I think it should be MAXIMUM. I also think students can stay on their parents insurance until 26, but since I do not know what the constant is for, I do not know if it is supposed to be this way for a different reason.

**Comment by STRML** [comment]
Fixed in #22.
